const planets = [
    {
        id: 1,
        name: "Mercury",
        position: 1,
        type: "telluric",
        radius: "2 439Km",
        tempMax: "427 celsius degrees",
        tempMin: "-183 celsius degree",
        picture: "https://fr.wikipedia.org/wiki/Mercure_(plan%C3%A8te)#/media/Fichier:Mercury_in_color_-_Prockter07_centered.jpg",
        pictureTitle: "Mercury in colors",
        pictureCopyright: "Messenger",
        pictureDate: 2008,
        created: new Date(),
    },
    {
        id: 2,
        name: "Venus",
        position: 2,
        type: "telluric",
        radius: "6 051Km",
        tempMax: "490 celsius degrees",
        tempMin: "446 celsius degrees",
        picture: "https://fr.wikipedia.org/wiki/V%C3%A9nus_(plan%C3%A8te)#/media/Fichier:Venus-real_color.jpg",
        pictureTitle: "Venus real colors, Mariner 10",
        pictureCopyright: "Mariner 10",
        pictureDate: 1974,
        created: new Date(),
    },
    {
        id: 3,
        name: "Earth",
        positionFromTheSun: 3,
        type: "telluric",
        radius: "6 378 Km",
        tempMax: "56,7 celsius degrees",
        tempMin: "-93,2 celsius degrees",
        picture: "https://fr.wikipedia.org/wiki/Terre#/media/Fichier:The_Blue_Marble_(remastered).jpg",
        pictureTitle: "The Blue Marble",
        pictureCopyright: "Apollo 17",
        pictureDate: 1972,
        numberOfMoons: 1,
        moons: [
            {
                id: 1,
                name: ["Earth 1", "Moon"],
                radius: "1 737 Km",
                tempMax: "123 celsius degrees",
                tempMin: "-233 celsius degree"
            }
        ],
        created: new Date(),
    },
    {
        id: 4,
        name: "Mars",
        position: 4,
        type: "telluric",
        radius: "3 396Km",
        tempMax: "293 celsius degrees",
        tempMin: "-143 celsius degrees",
        picture: "https://fr.wikipedia.org/wiki/Mars_(plan%C3%A8te)#/media/Fichier:Mars_Valles_Marineris_EDIT.jpg",
        pictureInfo: "Valle Marineris",
        pictureCopyright: "Viking",
        pictureDate: 1980,
        created: new Date(),
    },
    {
        id: 5,
        name: "Jupiter",
        position: 5,
        type: "gas giant",
        radius: "71 392Km",
        tempMax: "-108 celsius degrees",
        tempMin: "-161 celsius degrees",
        picture: "https://fr.wikipedia.org/wiki/Jupiter_(plan%C3%A8te)#/media/Fichier:Junopiter.jpg",
        pictureTitle: "Jupiter's winds",
        pictureCopyright: "Juno",
        pictureDate: 2020,
        created: new Date(),
    },
    {
        id: 6,
        name: "Saturne",
        position: 6,
        type: "gas giant",
        radius: "60 268Km",
        tempMax: "-139 celsius degrees",
        tempMin: "-189 celsius degrees",
        picture: "https://fr.wikipedia.org/wiki/Saturne_(plan%C3%A8te)#/media/Fichier:Saturn_during_Equinox.jpg",
        pictureTitle: "Saturne during equinox",
        pictureCopyright: "Cassini",
        pictureDate: 2008,
        created: new Date(),
    },
    {
        id: 7,
        name: "Uranus",
        position: 7,
        type: "ice giant",
        radius: "25 559Km",
        tempMax: "-139 celsius degrees",
        tempMin: "-189 celsius degrees",
        picture: "https://fr.wikipedia.org/wiki/Saturne_(plan%C3%A8te)#/media/Fichier:Saturn_during_Equinox.jpg",
        pictureTitle: "Saturne during equinox",
        pictureCopyright: "Cassini",
        pictureDate: 2008,
        created: new Date(),
    },
]

module.exports = planets;